from faker import Faker
import random

fake = Faker()

universities = [
    "University of Alberta", 
    "MacEwan University",
    "Concordia University of Edmonton",
    "Mount Royal University", 
    "The King's University", 
    "University of Calgary"
]

# chatgpt did dis part
departmentCoursePrefixes = {
    "Department of Accounting and Finance": "ACCT",
    "Department of Allied Health and Human Performance": "ACUP",
    "Department of Anthropology, Economics and Political Science": "AEPS",
    "Department of Arts and Cultural Management": "AGAD",
    "Department of Studio Arts": "ARTE",
    "Department of Physical Sciences": "ASTR",
    "Department of Communication": "BCSC",
    "Department of Biological Sciences": "BICM",
    "Department of Botany": "BOTN",
    "Department of Business": "BUSN",
    "Department of Chemistry": "CHEM",
    "Department of Chinese": "CHIN",
    "Department of Chemical Engineering": "CHME",
    "Department of Classics": "CLAS",
    "Department of Computing": "CMPT",
    "Department of Communication Skills": "CMSK",
    "Department of Comparative Literature": "COMP",
    "Department of Cooperative Education": "COOP",
    "Department of Corrections": "CORR",
    "Department of Counseling": "COSL",
    "Department of Creative Writing": "CRWR",
    "Department of Child and Youth Care": "CYCW",
    "Department of Design": "DESN",
    "Department of Disability Management and Work Performance": "DMWP",
    "Department of Disability Studies": "DSLC",
    "Department of Earth and Atmospheric Sciences": "EASC",
    "Department of Early Childhood Care and Support": "ECCS",
    "Department of Early Childhood Development": "ECDV",
    "Department of Economics": "ECON",
    "Department of Emergency Crisis Response": "ECRP",
    "Department of Education": "EDUC",
    "Department of Engineering, Computer": "ENCP",
    "Department of Engineering": "ENGG",
    "Department of English": "ENGL",
    "Department of English for Academic Purposes": "ENPH",
    "Department of Environmental Studies": "ENVS",
    "Department of Environmental Occupational Physiology and Therapy": "EOPT",
    "Department of Earth and Resource Development Work": "ERDW",
    "Department of Exploration Studies": "ESPL",
    "Department of Finance": "FNCE",
    "Department of Foundations": "FOUN",
    "Department of French": "FREN",
    "Department of Gender Studies": "GEND",
    "Department of Genetics": "GENE",
    "Department of German": "GERM",
    "Department of Greek": "GREK",
    "Department of Health and Physical Readiness": "HAPR",
    "Department of Health Education": "HEED",
    "Department of History": "HIST",
    "Department of Health Sciences": "HLSC",
    "Department of Health Studies": "HLST",
    "Department of Human Resource Management": "HRMT",
    "Department of Health Systems Administration": "HSAD",
    "Department of Humanities": "HUMN",
    "Department of Indigenous Studies": "INDG",
    "Department of Information Management": "INFM",
    "Department of Insect Studies": "INSE",
    "Department of Insurance": "INSR",
    "Department of Interdisciplinary Studies": "INTA",
    "Department of International Business": "INTB",
    "Department of Interior Design": "INTD",
    "Department of Japanese": "JAPN",
    "Department of Latin": "LATN",
    "Department of Legal Studies": "LEGL",
    "Department of Linguistics": "LING",
    "Department of Marketing": "MARK",
    "Department of Mathematics": "MATH",
    "Department of Management": "MGMT",
    "Department of Management Systems": "MGTS",
    "Department of Music Systems": "MSYS",
    "Department of Music Therapy Studies": "MTST",
    "Department of Music": "MUSC",
    "Department of Nursing": "NURS",
    "Department of Office Assistant Studies": "OAAS",
    "Department of Office Administration": "OADM",
    "Department of Office Administration and Legal Studies": "OALS",
    "Department of Office Administration and Medical Studies": "OAMS",
    "Department of Occupational Health": "OCCH",
    "Department of Out-of-School Care": "OOSC",
    "Department of Organizational Behavior": "ORGA",
    "Department of Public Administration and Business": "PABA",
    "Department of Physical Activity": "PACT",
    "Department of Psychiatric Nursing": "PBNS",
    "Department of Physical Education": "PEDS",
    "Department of Physical Education, Recreation, and Leisure Studies": "PERL",
    "Department of Physical Education and Sport Studies": "PESS",
    "Department of Philosophy": "PHIL",
    "Department of Physical Sciences": "PHSC",
    "Department of Physical Education and Sport Development": "PHSD",
    "Department of Physics": "PHYS",
    "Department of Property Management": "PMGT",
    "Department of Psychiatric Nursing": "PNRS",
    "Department of Political Science": "POLS",
    "Department of Public Relations": "PREL",
    "Department of Professional Writing": "PROW",
    "Department of Police and Security": "PSSC",
    "Department of Psychology": "PSYC",
    "Department of Science": "SCIE",
    "Department of Supply Chain Management": "SCMT",
    "Department of Sociology": "SOCI",
    "Department of Social Studies": "SOST",
    "Department of Social Work": "SOWK",
    "Department of Spanish": "SPAN",
    "Department of Statistics": "STAT",
    "Department of Sustainability": "SUST",
    "Department of Special Needs Educational Assistant": "TAST",
    "Department of Theatre": "THAR",
    "Department of Therapist Assistant": "THAS",
    "Department of Theatre Production": "THPR",
    "Department of Travel and Tourism": "TRVL",
    "Department of Urban Wellness": "URBW",
    "Department of Work Integrated Learning": "WINL",
    "Department of Writing": "WRIT",
    "Department of Zoology": "ZOOL",
}


departmentFacultyMapping = {
    "Department of Accounting and Finance": "Faculty of Business",
    "Department of Allied Health and Human Performance": "Faculty of Health Sciences",
    "Department of Anthropology, Economics and Political Science": "Faculty of Arts and Social Sciences",
    "Department of Arts and Cultural Management": "Faculty of Arts",
    "Department of Studio Arts": "Faculty of Arts",
    "Department of Physical Sciences": "Faculty of Science",
    "Department of Communication": "Faculty of Communication",
    "Department of Biological Sciences": "Faculty of Science",
    "Department of Botany": "Faculty of Science",
    "Department of Business": "Faculty of Business",
    "Department of Chemistry": "Faculty of Science",
    "Department of Chinese": "Faculty of Humanities",
    "Department of Chemical Engineering": "Faculty of Engineering",
    "Department of Classics": "Faculty of Humanities",
    "Department of Computing": "Faculty of Computing",
    "Department of Communication Skills": "Faculty of Communication",
    "Department of Comparative Literature": "Faculty of Humanities",
    "Department of Cooperative Education": "Faculty of Health Sciences",
    "Department of Corrections": "Faculty of Social Sciences",
    "Department of Counseling": "Faculty of Education",
    "Department of Creative Writing": "Faculty of Arts",
    "Department of Child and Youth Care": "Faculty of Health Sciences",
    "Department of Design": "Faculty of Arts",
    "Department of Disability Management and Work Performance": "Faculty of Health Sciences",
    "Department of Disability Studies": "Faculty of Health Sciences",
    "Department of Earth and Atmospheric Sciences": "Faculty of Science",
    "Department of Early Childhood Care and Support": "Faculty of Education",
    "Department of Early Childhood Development": "Faculty of Education",
    "Department of Emergency Crisis Response": "Faculty of Social Sciences",
    "Department of Engineering, Computer": "Faculty of Engineering",
    "Department of Engineering": "Faculty of Engineering",
    "Department of English": "Faculty of Arts",
    "Department of English for Academic Purposes": "Faculty of Arts",
    "Department of Environmental Studies": "Faculty of Environmental Studies",
    "Department of Environmental Occupational Physiology and Therapy": "Faculty of Health Sciences",
    "Department of Earth and Resource Development Work": "Faculty of Environmental Studies",
    "Department of Exploration Studies": "Faculty of Science",
    "Department of Finance": "Faculty of Business",
    "Department of Foundations": "Faculty of Education",
    "Department of French": "Faculty of Humanities",
    "Department of Gender Studies": "Faculty of Social Sciences",
    "Department of German": "Faculty of Humanities",
    "Department of Greek": "Faculty of Humanities",
    "Department of Health and Physical Readiness": "Faculty of Health Sciences",
    "Department of Health Education": "Faculty of Health Sciences",
    "Department of History": "Faculty of Humanities",
    "Department of Health Sciences": "Faculty of Health Sciences",
    "Department of Health Studies": "Faculty of Health Sciences",
    "Department of Human Resource Management": "Faculty of Business",
    "Department of Health Systems Administration": "Faculty of Health Sciences",
    "Department of Humanities": "Faculty of Humanities",
    "Department of Indigenous Studies": "Faculty of Humanities",
    "Department of Information Management": "Faculty of Information Technology",
    "Department of Insect Studies": "Faculty of Science",
    "Department of Insurance": "Faculty of Business",
    "Department of Interdisciplinary Studies": "Faculty of Arts",
    "Department of International Business": "Faculty of Business",
    "Department of Interior Design": "Faculty of Arts",
    "Department of Japanese": "Faculty of Humanities",
    "Department of Latin": "Faculty of Humanities",
    "Department of Legal Studies": "Faculty of Law",
    "Department of Linguistics": "Faculty of Humanities",
    "Department of Marketing": "Faculty of Business",
    "Department of Mathematics": "Faculty of Science",
    "Department of Management": "Faculty of Business",
    "Department of Management Systems": "Faculty of Business",
    "Department of Music Therapy Studies": "Faculty of Arts",
    "Department of Music": "Faculty of Arts",
    "Department of Nursing": "Faculty of Health Sciences",
    "Department of Office Assistant Studies": "Faculty of Business",
    "Department of Office Administration": "Faculty of Business",
    "Department of Office Administration and Legal Studies": "Faculty of Business",
    "Department of Office Administration and Medical Studies": "Faculty of Business",
    "Department of Occupational Health": "Faculty of Health Sciences",
    "Department of Out-of-School Care": "Faculty of Education",
    "Department of Organizational Behavior": "Faculty of Business",
    "Department of Public Administration and Business": "Faculty of Business",
    "Department of Physical Activity": "Faculty of Health Sciences",
    "Department of Psychiatric Nursing": "Faculty of Nursing",
    "Department of Physical Education": "Faculty of Education",
    "Department of Philosophy": "Faculty of Humanities",
    "Department of Physical Sciences": "Faculty of Science",
    "Department of Physical Education and Sport Development": "Faculty of Education",
    "Department of Physics": "Faculty of Science",
    "Department of Property Management": "Faculty of Business",
    "Department of Political Science": "Faculty of Social Sciences",
    "Department of Public Relations": "Faculty of Communication",
    "Department of Professional Writing": "Faculty of Arts",
    "Department of Police and Security": "Faculty of Social Sciences",
    "Department of Psychology": "Faculty of Social Sciences",
    "Department of Science": "Faculty of Science",
    "Department of Supply Chain Management": "Faculty of Business",
    "Department of Sociology": "Faculty of Social Sciences",
    "Department of Social Studies": "Faculty of Social Sciences",
    "Department of Social Work": "Faculty of Social Sciences",
    "Department of Spanish": "Faculty of Humanities",
    "Department of Statistics": "Faculty of Science",
    "Department of Sustainability": "Faculty of Environmental Studies",
    "Department of Special Needs Educational Assistant": "Faculty of Education",
    "Department of Theatre": "Faculty of Arts",
    "Department of Therapist Assistant": "Faculty of Health Sciences",
    "Department of Theatre Production": "Faculty of Arts",
    "Department of Travel and Tourism": "Faculty of Business",
    "Department of Urban Wellness": "Faculty of Health Sciences",
    "Department of Work Integrated Learning": "Faculty of Business",
    "Department of Writing": "Faculty of Humanities",
    "Department of Zoology": "Faculty of Science",
    "Department of Economics": "Faculty of Arts and Social Sciences",
    "Department of Education": "Faculty of Education", 
    "Department of Genetics": "Faculty of Science", 
    "Department of Music Systems": "Faculty of Arts", 
    "Department of Physical Education, Recreation, and Leisure Studies": "Faculty of Health Sciences", 
    "Department of Physical Education and Sport Studies": "Faculty of Health Sciences",

}

def generateCourses(universities, departmentCoursePrefixes, departmentFacultyMapping):
    courseList = []
    courseIdSet = set()

    for university in universities:
        # Each university gets a subset of departments
        availableDepartments = random.sample(list(departmentCoursePrefixes.keys()), k=len(departmentCoursePrefixes)//2 + 1)
        
        for department in availableDepartments:
            prefix = departmentCoursePrefixes[department]
            faculty = departmentFacultyMapping[department]

            # Generate a few courses for each department
            for i in range(random.randint(20, 100)):
                # unique course ID
                while True:
                    courseId = f"{prefix} {random.randint(100, 499)}"  # e.g., CHEM101
                    if courseId not in courseIdSet:
                        courseIdSet.add(courseId)
                        break

                courseList.append((courseId, department, faculty, university))

    return courseList

def saveToFile(courseList, filename):
    with open(filename, 'w') as file:
        for course in courseList:
            university = course[3].replace("'", "''")
            insertStatement = f"INSERT INTO course (courseID, department, faculty, university) VALUES ('{course[0]}', '{course[1]}', '{course[2]}', '{university}');\n"
            file.write(insertStatement)

courseData = generateCourses(universities, departmentCoursePrefixes, departmentFacultyMapping)
saveToFile(courseData, 'courses_data.sql')
